--- tastypie/resources.py.orig	2020-08-24 13:14:25.463166100 +0200
+++ tastypie/resources.py	2020-08-24 13:15:55.133759224 +0200
@@ -15,7 +15,7 @@
     ObjectDoesNotExist, MultipleObjectsReturned, ValidationError, FieldDoesNotExist
 )
 from django.core.signals import got_request_exception
-from django.core.exceptions import ImproperlyConfigured
+from django.core.exceptions import ImproperlyConfigured, FieldError
 from django.db.models.fields.related import ForeignKey
 try:
     from django.contrib.gis.db.models.fields import GeometryField
@@ -2207,6 +2207,8 @@
             return self.authorized_read_list(objects, bundle)
         except ValueError:
             raise BadRequest("Invalid resource lookup data provided (mismatched type).")
+        except FieldError as e:
+            raise BadRequest("Invalid resource lookup: %s." % e)
 
     def obj_get(self, bundle, **kwargs):
         """
